#!/usr/bin/env bash
#iterates from 0 to 1 and echos differently
count=0
while [ $count -lt 8 ]
do
	echo "Best School"
	((count++))
	if [ $count == 3 ]
	then
		echo "bad luck"
	elif [ $count == 6 ]
	then
		echo "good luck"
	fi
done		
